// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4ZOiBIFiB67KNNqVVCZSI23DlWYrVVkY',
    appId: '1:588460462664:web:1622d4fda390a32e503e7d',
    messagingSenderId: '588460462664',
    projectId: 'eduvest-bendahara',
    authDomain: 'eduvest-bendahara.firebaseapp.com',
    storageBucket: 'eduvest-bendahara.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7wzkuoXBH_H93tFWS0Ok56Bw5KjP7Ty8',
    appId: '1:588460462664:android:431c0a14edde5ff1503e7d',
    messagingSenderId: '588460462664',
    projectId: 'eduvest-bendahara',
    storageBucket: 'eduvest-bendahara.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmICjmOzt6SvQX5A1U34Qdpw1Y_97rGnU',
    appId: '1:588460462664:ios:ff82de534609ae4b503e7d',
    messagingSenderId: '588460462664',
    projectId: 'eduvest-bendahara',
    storageBucket: 'eduvest-bendahara.firebasestorage.app',
    iosBundleId: 'com.example.bendahara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmICjmOzt6SvQX5A1U34Qdpw1Y_97rGnU',
    appId: '1:588460462664:ios:ff82de534609ae4b503e7d',
    messagingSenderId: '588460462664',
    projectId: 'eduvest-bendahara',
    storageBucket: 'eduvest-bendahara.firebasestorage.app',
    iosBundleId: 'com.example.bendahara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD4ZOiBIFiB67KNNqVVCZSI23DlWYrVVkY',
    appId: '1:588460462664:web:455f0e17f5de19f2503e7d',
    messagingSenderId: '588460462664',
    projectId: 'eduvest-bendahara',
    authDomain: 'eduvest-bendahara.firebaseapp.com',
    storageBucket: 'eduvest-bendahara.firebasestorage.app',
  );
}
